### ISSUE TITLE
Is it possible to support support files in sub-folders?

### ISSUE THREAD

**Issue by wenlzhang** [nschloe/blacktex#15]
Currently, it seems that only the main `.tex` file can be formatted. Is it also possible to support files imported with `\input{folder/file.tex}`?

**Comment by nschloe** [comment]
You can simply run blacktex on those files, right?

**Comment by wenlzhang** [comment]
Yes. But it may be more convenient if they can be handled by only running the command once, if there are many files, say, when writing a book or thesis?

**Comment by nschloe** [comment]
You can run blacktex on all tex files at once, e.g.,
```
find -name *.tex | xargs blacktex -
```
I think trying to handle this from within blacktex adds more code without good  reason. The only thing I could imagine having in blacktex is a `-r` switch for recursive "blacking". I'll be more than happy to review PRs for it.

**Comment by wenlzhang** [comment]
Thanks for the prompt reply. Having a switch like this would also be helpful. Is this already supported in the current version of blacktex? Also, with such a switch, does one need to change all the file names within `\input{folder/file.tex}`? Or one can do something like `blacktex in.tex in.tex` such that all file names can be the same as their original ones?

**Comment by nschloe** [comment]
> Is this already supported in the current version of blacktex?

No, not yet, but if you or someone else does it then it'll be ready fast.

>  Also, with such a switch, does one need to change all the file names within \input{folder/file.tex}?

The idea would be that `-r` runs on all tex files in a given folder (like almost all `-r` switches on command-line programs).

**Comment by nschloe** [comment]
Closing since there is nothing actionable for me right now.
