### ISSUE TITLE
Blacktex dangerously reformats commented-out code even with `--keep-comments` option

### ISSUE THREAD

**Issue by krishnakumarg1984** [nschloe/blacktex#40]
Consider the following commented-out latex snippet:

``` tex
% Because   of $$a+b=c$$ ({\it Pythogoras}),
% % @johnny remember to insert name
% and $y=2^ng$ with $n=1,...,10$, we have ${\Gamma \over 2}=8.$
```
When we run `blacktex` on this file with the `--keep-comments` option, the text is modified to:

``` tex
% Because of
\[
a+b = c
\]
(\textit{Pythogoras}),
% % @johnny remember to insert name
% and \(y = 2^n g\) with \(n = 1,\dots,10\), we have \(\frac{\Gamma}{2} = 8\).
```

Note that the equation `a+b=c` will get typeset in the PDF output, despite the user's intention to keep it commented out. This is dangerous, and such silent side effects can be impossible to detect in a large document.

**Comment by nschloe** [comment]
Good point!

**Comment by krishnakumarg1984** [comment]
Also, `\textit{Pythogoras}` gets uncommented too!

Furthermore, `\it` should not be transformed to `\textit`, but rather than to `\emph` (this is the more semantic description of emphasizing, rather than telling _how_ to emphasize). They both produce the same result when used within standard text, but `\emph` should be used in modern contexts. See [https://tex.stackexchange.com/questions/1980/emph-or-textit](https://tex.stackexchange.com/questions/1980/emph-or-textit).

**Comment by krishnakumarg1984** [comment]
Any update on this?

**Comment by nschloe** [comment]
So, I made some headway in this direction when trying out an actual LaTeX parser. This is probably as good as it gets. If there are any more issues that you have, feel free to PR!
