### ISSUE TITLE
Removes spaces in \text environment

### ISSUE THREAD

**Issue by cuppajoeman** [nschloe/blacktex#48]
If someone uses spaces (trailing at the start or end) in \text{ ... } environment, they are removed. Is this the intended functionality (this actually changes the output of the latex file as it changes the spacing)

**Comment by nschloe** [comment]
Yeah, I used to use those spaces in the same way. It's probably better to be explicit with spacing after text with a `\,` or `\quad` though. Let's leave this open in case I decide to address this in the future.

**Comment by cuppajoeman** [comment]
Yeah, I use ~\text{blah blah}~ now to avoid this which is probably better practice. But I have some older latex code which I can't use blacktex on because of this.

**Comment by cuppajoeman** [comment]
For some reason blacktex also removes ~'s when I tried to do what I mentioned in the above comment: 

![tilde](https://user-images.githubusercontent.com/19198104/141198274-4a4d4c7c-657f-46e2-97e4-eff3be6cf1a5.gif)

**Comment by nschloe** [comment]
`~` is a non-breaking space, so it doesn't make sense to put it next to a breaking space. blacktex replaces `~ ` and ` ~` by ` `.
