### ISSUE TITLE
Line Breaking

### ISSUE THREAD

**Issue by cuppajoeman** [nschloe/blacktex#49]
When I write latex, I find it enjoyable to have the tex file have line breaks at a certain horizontal limit:

![image](https://user-images.githubusercontent.com/19198104/140876187-5131ae87-7919-44fb-9081-61d200dc0873.png)

How hard would it be to implement an option into the formatter which can enforce a line width? 

I would be able to help implement this if you can direct me where to go.

**Comment by nschloe** [comment]
Probably out of scopy for blacktex.

**Comment by cuppajoeman** [comment]
Sounds good.
