### ISSUE TITLE
Add a `conda` install option to `blacktex`

### ISSUE THREAD

**Issue by sugatoray** [nschloe/blacktex#50]
A conda install option as an alternative to pip installing from PyPI could be useful. I have already added `blacktex` to conda-forge (PR: https://github.com/conda-forge/staged-recipes/pull/17224). 

I will send a PR to add the following to the readme.

```sh
conda install -c conda-forge blacktex
```

**Comment by sugatoray** [comment]
cc: @nschloe

**Comment by nschloe** [comment]
-> #52.
