### ISSUE TITLE
Adding backslash to keywords outside of math mode

### ISSUE THREAD

**Issue by samrobbins85** [nschloe/blacktex#7]
This program adds a backslash to keywords such as min and max, however, this only works inside of math mode as \min is not valid outside of it. To fix this problem, it should be detected if the keyword is in math mode, and if it is, then do the same as it currently does, but if the keyword is not in math mode, then the characters to put the keyword into math mode should be inserted

**Comment by nschloe** [comment]
For this to work, blacktex will have to be a LaTeX parser which is _way_ to complex for a package like this. We can use heuristics though which work in most of the cases. The heuristic for keywords like `min` is to replace it by `\min` if it's not proceeded or succeeded by a letter as in, e.g., `minimum`. What's the exact context of your finding?

**Comment by samrobbins85** [comment]
This is true, it's up to you of course. Just thought I would mention this behaviour as it can lead to LaTeX that has errors

**Comment by nschloe** [comment]
If you show me the snippet of code that produced the false positive, I can try and fix that case.

**Comment by samrobbins85** [comment]
An example of this would be `take the min of the two values`, which is shorthand for minimum, but could be used outside of math mode in brief notes

**Comment by nschloe** [comment]
Yeah, this is a tough one. The regex is to add a backslash if `min` is not preceded or succeeded by a letter, such as in "minimum" or "jasmin". I'd vote for keeping it the way it is: If one uses abbreviations like that, you'll have to expect failures. They are so easy to fix though and this is better than skipping a `\min` to often.
